[package]
name = "day-01"
version = "0.1.0"
edition = "2021"
description = " Advent of code 2023 day one problem"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
